"""
vqd_excited_states.py
---------------------
Variational Quantum Deflation (VQD) to find the lowest 3 eigenvalues of the
H2/STO-3G Jordan-Wigner Hamiltonian using QtorchX's gate library.

Algorithm
---------
State 0: VQE  →  minimise  ⟨ψ₀|H|ψ₀⟩
State 1: VQD  →  minimise  ⟨ψ₁|H|ψ₁⟩ + β|⟨ψ₀|ψ₁⟩|²
State 2: VQD  →  minimise  ⟨ψ₂|H|ψ₂⟩ + β(|⟨ψ₀|ψ₂⟩|² + |⟨ψ₁|ψ₂⟩|²)

Run:
    cd <repo_root>
    python excited_states/vqd_excited_states.py

Outputs:
    excited_states/vqd_results.npz  — energies + loss history
"""

import sys, os, json
import numpy as np
import torch

if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
if hasattr(sys.stderr, "reconfigure"):
    try:
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

# ── Path setup ────────────────────────────────────────────────────────────────
_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.join(_HERE, "..")
sys.path.insert(0, _REPO)

from excited_states.ansatz import HEAnsatz, expectation, overlap_penalty


# ── Config ────────────────────────────────────────────────────────────────────
N_QUBITS   = 4
N_LAYERS   = 3      # depth-3 HEA; deeper = more expressive
LR         = 0.05
N_EPOCHS   = 30
BETA       = 8.0    # deflation penalty weight
PRINT_EVERY = 25

HAM_FILE   = os.path.join(_HERE, "h2_hamiltonian.npy")
OUT_FILE   = os.path.join(_HERE, "vqd_results.npz")

# Known STO-3G JW H2 Pauli decomposition (fallback if .npy not yet generated).
# Coefficients at r = 0.735 Å from multiple published sources.
_PAULI_TERMS = [
    # (coefficient,  pauli_string)   qubit ordering: 0 = most-significant bit
    (-0.09706626816762845, "IIII"),
    ( 0.17141282644776895, "IIIZ"),
    (-0.22343153690813597, "IIZI"),
    (-0.22343153690813597, "IZII"),
    ( 0.17141282644776895, "ZIII"),
    ( 0.16868898170361218, "IIZZ"),
    ( 0.12054482205828003, "IZIZ"),
    ( 0.16592785033770352, "IZZI"),
    ( 0.16592785033770352, "ZIIZ"),
    ( 0.12054482205828003, "ZIZI"),
    ( 0.17441287612261608, "ZZII"),
    ( 0.04530261550380005, "YXXY"),
    (-0.04530261550380005, "YYXX"),
    (-0.04530261550380005, "XXYY"),
    ( 0.04530261550380005, "XYYX"),
]


def _pauli_mat(c: str) -> np.ndarray:
    mats = {
        "I": np.eye(2, dtype=complex),
        "X": np.array([[0, 1], [1, 0]], dtype=complex),
        "Y": np.array([[0, -1j], [1j, 0]], dtype=complex),
        "Z": np.array([[1, 0], [0, -1]], dtype=complex),
    }
    return mats[c]


def _build_fallback_hamiltonian() -> np.ndarray:
    """Build 16×16 H2 Hamiltonian from hardcoded Pauli terms (no PySCF needed)."""
    dim = 2 ** N_QUBITS
    H = np.zeros((dim, dim), dtype=complex)
    for coeff, pstr in _PAULI_TERMS:
        mat = _pauli_mat(pstr[0])
        for c in pstr[1:]:
            mat = np.kron(mat, _pauli_mat(c))
        H += coeff * mat
    return H


def load_hamiltonian() -> torch.Tensor:
    """
    Load Hamiltonian from .npy (generated by generate_hamiltonian.py).
    Falls back to hardcoded Pauli decomposition if file not found.
    """
    if os.path.exists(HAM_FILE):
        H_np = np.load(HAM_FILE).astype(np.complex128)
        print(f"[Load] Hamiltonian from {HAM_FILE}  shape={H_np.shape}")
    else:
        print(f"[Warning] {HAM_FILE} not found — using hardcoded fallback Hamiltonian.")
        print("         Run `python excited_states/generate_hamiltonian.py` for exact values.")
        H_np = _build_fallback_hamiltonian()
        print(f"[Fallback] Hamiltonian built from Pauli terms  shape={H_np.shape}")

    H = torch.tensor(H_np, dtype=torch.complex128)

    # Sanity: Hermitian check
    err = float(torch.max(torch.abs(H - H.conj().T)))
    if err > 1e-8:
        raise ValueError(f"Hamiltonian is not Hermitian (err={err:.2e})")

    # Print exact eigenvalues for reference
    eigvals = torch.linalg.eigvalsh(H).numpy()
    print(f"\n[Reference] Exact eigenvalues (numpy):")
    for i in range(min(6, len(eigvals))):
        print(f"  E{i} = {eigvals[i]:+.8f} Ha")

    return H


def run_vqe_vqd(H: torch.Tensor) -> dict:
    """
    Run VQE (state 0) then VQD (states 1 and 2).

    Returns a dict with keys:
        energies      : [E0, E1, E2]
        states        : list of converged statevectors (complex128 tensors)
        loss_history  : [[losses for state 0], [losses for state 1], [losses for state 2]]
    """
    found_states   = []   # converged statevectors (detached)
    energies       = []
    loss_histories = []

    for state_idx in range(3):
        label = "VQE" if state_idx == 0 else f"VQD (state {state_idx})"
        print(f"\n{'='*60}")
        print(f"  {label}")
        print(f"{'='*60}")

        # Fresh ansatz for each state (independent parameters)
        torch.manual_seed(42 + state_idx * 7)
        ansatz = HEAnsatz(n_qubits=N_QUBITS, n_layers=N_LAYERS)
        optimizer = torch.optim.Adam(ansatz.parameters(), lr=LR)

        history = []

        for epoch in range(N_EPOCHS):
            optimizer.zero_grad()

            psi  = ansatz()                                     # (16,) complex128
            E    = expectation(H, psi)                         # scalar real
            pen  = overlap_penalty(psi, found_states, BETA)    # scalar real
            loss = E + pen

            loss.backward()
            optimizer.step()

            history.append({
                "epoch":   epoch,
                "energy":  float(E.item()),
                "penalty": float(pen.item()),
                "loss":    float(loss.item()),
            })

            if (epoch + 1) % PRINT_EVERY == 0 or epoch == 0:
                e_val = float(E.detach().item())
                pen_val = float(pen.detach().item())
                loss_val = float(loss.detach().item())
                print(
                    f"  Epoch {epoch+1:3d}/{N_EPOCHS}"
                    f"  E = {e_val:+.6f} Ha"
                    f"  penalty = {pen_val:.6f}"
                    f"  loss = {loss_val:+.6f}"
                )

        # ── Convergence summary ───────────────────────────────────────────
        with torch.no_grad():
            final_psi = ansatz()
            final_E   = float(expectation(H, final_psi))

        print(f"\n  → Final energy E{state_idx} = {final_E:+.8f} Ha")

        # Store for next state's penalty
        found_states.append(final_psi.detach().clone())
        energies.append(final_E)
        loss_histories.append(history)

    return {
        "energies":      energies,
        "states":        found_states,
        "loss_history":  loss_histories,
    }


def print_summary(results: dict, H: torch.Tensor):
    exact = torch.linalg.eigvalsh(H).numpy()

    print("\n" + "=" * 60)
    print("  VQD RESULTS vs EXACT")
    print("=" * 60)
    print(f"  {'State':<8} {'VQD energy':>14}  {'Exact':>14}  {'Error':>10}")
    print(f"  {'-'*8} {'-'*14}  {'-'*14}  {'-'*10}")
    for i, (e_vqd, e_exact) in enumerate(zip(results["energies"], exact[:3])):
        err = abs(e_vqd - e_exact)
        print(f"  E{i:<7} {e_vqd:>+14.8f}  {e_exact:>+14.8f}  {err:>10.2e}")
    print("=" * 60)

    # Cross-overlaps between found states (should be ~0)
    print("\n  Overlap matrix |⟨ψᵢ|ψⱼ⟩|²:")
    states = results["states"]
    for i in range(3):
        row = []
        for j in range(3):
            ov = float(torch.abs(torch.conj(states[i]) @ states[j]) ** 2)
            row.append(f"{ov:.4f}")
        print(f"    ψ{i}: [{', '.join(row)}]")


def save_results(results: dict, H: torch.Tensor):
    exact = torch.linalg.eigvalsh(H).numpy()

    loss_e0 = [x["energy"] for x in results["loss_history"][0]]
    loss_e1 = [x["energy"] for x in results["loss_history"][1]]
    loss_e2 = [x["energy"] for x in results["loss_history"][2]]

    penalty_e1 = [x["penalty"] for x in results["loss_history"][1]]
    penalty_e2 = [x["penalty"] for x in results["loss_history"][2]]

    np.savez(
        OUT_FILE,
        vqd_energies      = np.array(results["energies"]),
        exact_eigenvalues  = exact,
        loss_e0           = np.array(loss_e0),
        loss_e1           = np.array(loss_e1),
        loss_e2           = np.array(loss_e2),
        penalty_e1        = np.array(penalty_e1),
        penalty_e2        = np.array(penalty_e2),
        n_epochs          = np.array([N_EPOCHS]),
        beta              = np.array([BETA]),
    )
    print(f"\n[Saved] Results → {OUT_FILE}")


def main():
    print("QtorchX  ·  VQD Excited States Demo")
    print("H₂ molecule  ·  STO-3G basis  ·  Jordan-Wigner encoding")
    print(f"Ansatz: HEA  n_qubits={N_QUBITS}  n_layers={N_LAYERS}  params={(N_LAYERS+1)*N_QUBITS}")
    print(f"Optimizer: Adam  lr={LR}  epochs={N_EPOCHS}  beta={BETA}")

    H       = load_hamiltonian()
    results = run_vqe_vqd(H)

    print_summary(results, H)
    save_results(results, H)

    return results


if __name__ == "__main__":
    main()
